Product/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('create_product/', create_product, name='create_product'),
    path('', product_view, name='product_view'),
    path('<uuid:uuid>/', right_product_view, name='right_product_view'),
    path('create/banner/', banner_create_view, name='create_banner'),
    path('create/banner2/', banner2_create_view, name='create_banner2'),
    path('create/deal/', deal_create_view, name='create_deal'),
    path('create/featured_brand/', featured_brand_create_view, name='create_featured_brand'),
    path('success/', success_view, name='success'),
    path('creation/dashboard/view/', creation_dashboard_view, name='creation_dashboard_view'),
    path('submit_review',submit_review, name='submit_review')
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import home_view, all_product_viow, quick_view

urlpatterns = [
    path('', home_view, name='home'),
    path('products/', all_product_viow, name='all_product'),
    path('quick_view/<uuid:uuid>/', quick_view, name='quick_view'),
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('auth/', include('Auth_App.urls')),
    path('account/', include('Account_Dashboard.urls')),
    path('product/', include('Product.urls')),
    path('cart/', include('cart_and_check_out.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Product/models.py
import uuid
from django.db import models
from .utils import convert_image_size


class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cat_logo = models.ImageField(upload_to='category_logos/', blank=True, null=True)

    def __str__(self):
        return self.name

class SubCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='subcategories')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    old_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    discount =models.CharField(max_length=50, blank=True, null=True)
    brand = models.CharField(max_length=50, blank=True, null=True)
    warranty = models.CharField(max_length=50, blank=True, null=True)
    sku = models.CharField(max_length=100, unique=True)
    quantity = models.PositiveIntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, related_name='products', blank=True, null=True)
    image = models.ImageField(upload_to='products/', blank=True, null=True)
    image2 = models.ImageField(upload_to='products/', blank=True, null=True)
    image3 = models.ImageField(upload_to='products/', blank=True, null=True)
    image4 = models.ImageField(upload_to='products/', blank=True, null=True)
    image5 = models.ImageField(upload_to='products/', blank=True, null=True)
    image6 = models.ImageField(upload_to='products/', blank=True, null=True)
    image7 = models.ImageField(upload_to='products/', blank=True, null=True)
    rating = models.PositiveIntegerField( null=True, blank=True)
    num_reviews = models.PositiveIntegerField(default=0)
    show_rating = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def save(self, *args, **kwargs):
        if self.old_price != 0:
            discount = self.old_price - self.price
            self.discount = round((discount / self.old_price) * 100)
        else:
            self.discount = 0
            
        try:
            self.image = convert_image_size(self.image, 10, 9)
            self.image2 = convert_image_size(self.image2, 10, 9)
            self.image3 = convert_image_size(self.image3, 10, 9)
            self.image4 = convert_image_size(self.image4, 10, 9)
            self.image5 = convert_image_size(self.image5, 10, 9)
            self.image6 = convert_image_size(self.image6, 10, 9)
            self.image7 = convert_image_size(self.image7, 10, 9)
        except:
            None
        super().save(*args, **kwargs)
        
    def __str__(self):
        return self.name
    
    
class Reviews(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    comment = models.TextField(blank=True, null=True)
    rating = models.PositiveIntegerField( null=True, blank=True)
    reply = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.name}'s Reviews: {self.comment}"
    
class Banner(models.Model):
    title_small = models.CharField(max_length=255, help_text="Small title above main title")
    title_large = models.TextField(help_text="Main large title")
    image = models.ImageField(upload_to='banners/', help_text="Image for the banner")
    button_text = models.CharField(max_length=100, help_text="Text displayed on the button")
    button_link = models.URLField(max_length=200, help_text="URL that the button links to")
    
    def save(self, *args, **kwargs):
        img = convert_image_size(self.image, 13, 3)
        self.image = img
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.title_large


class Banner_2(models.Model):
    small_title = models.CharField(max_length=255, help_text="Small title above the main title")
    large_title = models.TextField(help_text="Main large title")
    image = models.ImageField(upload_to='banners/', help_text="Image for the banner")
    button_link = models.URLField(max_length=200, help_text="URL that the button links to")
    
    def __str__(self):
        return self.large_title


class Deal(models.Model):
    title = models.CharField(max_length=255, help_text="Title of the deal")
    subtitle = models.CharField(max_length=255, blank=True, null=True, help_text="Subtitle of the deal")
    description = models.TextField(blank=True, null=True, help_text="Description of the deal")
    image = models.ImageField(upload_to='deals/', help_text="Background image for the deal")
    new_price = models.DecimalField(max_digits=10, decimal_places=2, help_text="New price of the deal")
    old_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, help_text="Old price of the deal")
    countdown_end = models.DateTimeField(help_text="End date and time for the countdown")
    product_link = models.URLField(max_length=200, help_text="Link to the product")
    shop_link = models.URLField(max_length=200, help_text="Link to the shop page")

    def __str__(self):
        return self.title
    
class FeaturedBrand(models.Model):
    name = models.CharField(max_length=255, help_text="Name of the brand")
    image = models.ImageField(upload_to='brands/', help_text="Logo of the brand")

    def __str__(self):
        return self.name

Product/forms.py
from django import forms
from .models import Banner, Banner_2, Deal, FeaturedBrand, Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'old_price', 'brand', 'warranty', 'sku', 'quantity', 'category', 'subcategory', 'image', 'image2', 'image3', 'image4', 'image5', 'image6', 'image7']

class BannerForm(forms.ModelForm):
    class Meta:
        model = Banner
        fields = '__all__'

class Banner2Form(forms.ModelForm):
    class Meta:
        model = Banner_2
        fields = '__all__'

class DealForm(forms.ModelForm):
    class Meta:
        model = Deal
        fields = '__all__'

class FeaturedBrandForm(forms.ModelForm):
    class Meta:
        model = FeaturedBrand
        fields = '__all__'

Product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, Category, SubCategory, Reviews
from .forms import BannerForm, Banner2Form, DealForm, FeaturedBrandForm, ProductForm
from django.contrib import messages





def create_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')  # Redirect to a success page or another page
    else:
        form = ProductForm()
    return render(request, 'product/Create Views/create_product.html', {'form': form})


def product_view(request):
    products = Product.objects.all()
    return render(request, 'product/product_view.html')



def right_product_view(request , uuid):
    product = get_object_or_404(Product, uuid = uuid)
    reviews = Reviews.objects.filter(product=product)
    ratings = 0
    try:
        num_review = len(reviews)
        rate = 0
        star_1=0
        star_2=0
        star_3=0
        star_4=0
        star_5=0
        star_slider_1=0
        star_slider_2=0
        star_slider_3=0
        star_slider_4=0
        star_slider_5=0
        show_rating = 0
        for i in reviews:
            rate += i.rating

        show_rating = rate/num_review
        ratings =show_rating/20
        if ratings not in {5, 4, 3, 2, 1}:
            ratings = round(ratings,1)
        for i in reviews:
            if i.rating == 20:
                star_1 +=1
            elif i.rating == 40:
                star_2 +=1
            elif i.rating == 60:
                star_3 +=1
            elif i.rating == 80:
                star_4 +=1
            elif i.rating == 100:
                star_5+=1
        if num_review > 0:
            star_slider_1 = round((star_1 / num_review) * 100)
            star_slider_2 = round((star_2 / num_review) * 100)
            star_slider_3 = round((star_3 / num_review) * 100)
            star_slider_4 = round((star_4 / num_review) * 100)
            star_slider_5 = round((star_5 / num_review) * 100)
        else:
            star_slider_1 = 0
            star_slider_2 = 0
            star_slider_3 = 0
            star_slider_4 = 0
            star_slider_5 = 0
    except:
        None

    
    product.num_reviews = num_review
    if ratings:
        product.rating = ratings
        product.show_rating= show_rating
        product.save()

    if request.method == 'POST':
        comment = request.POST.get("comment")
        rating = request.POST.get('rating')
        if rating:
            rating = rating
        else:
            rating = 0
        if request.user.is_authenticated:
            name =f"{ request.user.first_name} { request.user.last_name}"
            print(name, rating)
            product = get_object_or_404(Product, uuid=uuid)
            Reviews.objects.create(comment=comment, rating=rating, name=name, product=product, )
            messages.success(request, 'Your review has been submitted.')
            
            return redirect(request.META.get('HTTP_REFERER', '/'))
        else:
            messages.error(request, 'You must be logged in to submit a review.')
            return redirect('login_registration')


    return render(request, 'product/full_product_view.html', {
        'product':product,
        'reviews':reviews,
        'star_slider_1':star_slider_1,
        'star_slider_2':star_slider_2,
        'star_slider_3':star_slider_3,
        'star_slider_4':star_slider_4,
        'star_slider_5':star_slider_5,
        
        })





def banner_create_view(request):
    if request.method == 'POST':
        form = BannerForm(request.POST, request.FILES)
        if form.is_valid():
            print ('is it okay')
            form.save()
            return redirect('success') 
        else:
            print('it  not okay')
    else:
        form = BannerForm()
    return render(request, 'product/Create Views/create_banner.html', {'form': form})

def banner2_create_view(request):
    if request.method == 'POST':
        form = Banner2Form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('success')
    else:
        messages.warning(request, 'not work')
        form = Banner2Form()
    return render(request, 'product/Create Views/create_banner2.html', {'form': form})

def deal_create_view(request):
    if request.method == 'POST':
        form = DealForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('success')
    else:
        form = DealForm()
    return render(request, 'product/Create Views/create_deal.html', {'form': form})

def featured_brand_create_view(request):
    if request.method == 'POST':
        form = FeaturedBrandForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('success')
    else:
        form = FeaturedBrandForm()
    return render(request, 'product/Create Views/create_featured_brand.html', {'form': form})

def success_view(request):
    return render(request, 'product/Create Views/success.html')


def creation_dashboard_view(request):
    return render(request, 'product/creation_dashboard.html')


# views.py
from django.shortcuts import render, redirect

def submit_review(request):
    if request.method == 'POST':
        rating = request.POST.get('rating')
        if rating:
            print(f"Received rating: {rating}")
            
    return render(request, 'template.html')

templates/product/Create Views/create_banner.html
<!-- create_banner.html -->
{% extends 'base/base.html' %}

{% block title %}Create Banner{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2>Create Banner</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_title_small" class="form-label">Small Title</label>
                {{ form.title_small }}
            </div>
            <div class="mb-3">
                <label for="id_title_small" class="form-label">Large Title</label>
                {{ form.title_large }}
            </div>
            <div class="mb-3">
                <label for="id_image" class="form-label">Image</label>
                {{ form.image }}
            </div>
            <div class="mb-3">
                <label for="id_button_text" class="form-label">Button Text</label>
                {{ form.button_text }}
            </div>
            <div class="mb-3">
                <label for="id_button_link" class="form-label">Button Link</label>
                {{ form.button_link }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

templates/product/Create Views/create_banner2.html
<!-- create_banner2.html -->
{% extends 'base/base.html' %}

{% block title %}Create Banner 2{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2>Create Banner 2</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
           
            <div class="mb-3">
                <label for="id_small_title" class="form-label">Small Title</label>
                {{ form.small_title }}
            </div>
            <div class="mb-3">
                <label for="id_small_title" class="form-label">Large Title</label>
                {{ form.large_title }}
            </div>
            <div class="mb-3">
                <label for="id_image" class="form-label">Image</label>
                {{ form.image }}
            </div>
            <div class="mb-3">
                <label for="id_button_link" class="form-label">Button Link</label>
                {{ form.button_link }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

templates/product/Create Views/create_deal.html
<!-- create_deal.html -->
{% extends 'base/base.html' %}

{% block title %}Create Deal{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2>Create Deal</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_title" class="form-label">Title</label>
                {{ form.title }}
            </div>
            <div class="mb-3">
                <label for="id_subtitle" class="form-label">Subtitle</label>
                {{ form.subtitle }}
            </div>
            <div class="mb-3">
                <label for="id_description" class="form-label">Description</label>
                {{ form.title }}
            </div>
            <div class="mb-3">
                <label for="id_image" class="form-label">Image</label>
                {{ form.image }}
            </div>
            <div class="mb-3">
                <label for="id_new_price" class="form-label">New Price</label>
                {{ form.new_price }}
            </div>
            <div class="mb-3">
                <label for="id_old_price" class="form-label">Old Price</label>
                {{ form.old_price }}
            </div>
            <div class="mb-3">
                <label for="id_countdown_end" class="form-label">Countdown End</label>
                {{ form.countdown_end }}
            </div>
            <div class="mb-3">
                <label for="id_product_link" class="form-label">Product Link</label>
                {{ form.product_link }}
            </div>
            <div class="mb-3">
                <label for="id_shop_link" class="form-label">Shop Link</label>
                {{ form.shop_link }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

templates/product/Create Views/create_featured_brand.html
<!-- create_featured_brand.html -->
{% extends 'base/base.html' %}

{% block title %}Create Featured Brand{% endblock %}

{% block content %}
    <div class=" container mt-5">
        <h2>Create Featured Brand</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_name" class="form-label">Name</label>
                {{ form.name }}
            </div>
            <div class="mb-3">
                <label for="id_image" class="form-label">Logo Image</label>
                {{ form.image }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

templates/product/Create Views/create_product.html
<!-- create_product.html -->
{% extends 'base/base.html' %}

{% block title %}Create Product{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2>Create Product</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_name" class="form-label">Name</label>
                {{ form.name }}
            </div>
            <div class="mb-3">
                <label for="id_description" class="form-label">Description</label>
                {{ form.description }}
            </div>
            <div class="mb-3">
                <label for="id_price" class="form-label">Price</label>
                {{ form.price }}
            </div>
            <div class="mb-3">
                <label for="id_old_price" class="form-label">Old Price</label>
                {{ form.old_price }}
            </div>
            <div class="mb-3">
                <label for="id_brand" class="form-label">Brand</label>
                {{ form.brand }}
            </div>
            <div class="mb-3">
                <label for="id_warranty" class="form-label">Warranty</label>
                {{ form.warranty }}
            </div>
            <div class="mb-3">
                <label for="id_sku" class="form-label">SKU</label>
                {{ form.sku }}
            </div>
            <div class="mb-3">
                <label for="id_quantity" class="form-label">Quantity</label>
                {{ form.quantity }}
            </div>
            <div class="mb-3">
                <label for="id_category" class="form-label">Category</label>
                {{ form.category }}
            </div>
            <div class="mb-3">
                <label for="id_subcategory" class="form-label">Subcategory</label>
                <select name="subcategory" id="id_subcategory" class="form-select">
                    {% for category in categories %}
                    <optgroup label="{{ category.name }}">
                        {% for subcategory in category.subcategories.all %}
                        <option value="{{ subcategory.id }}">{{ subcategory.name }}</option>
                        {% endfor %}
                    </optgroup>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="id_image" class="form-label">Image</label>
                {{ form.image }}
            </div>
            <div class="mb-3">
                <label for="id_image2" class="form-label">Image 2</label>
                {{ form.image2 }}
            </div>
            <div class="mb-3">
                <label for="id_image3" class="form-label">Image 3</label>
                {{ form.image3 }}
            </div>
            <div class="mb-3">
                <label for="id_image4" class="form-label">Image 4</label>
                {{ form.image4 }}
            </div>
            <div class="mb-3">
                <label for="id_image5" class="form-label">Image 5</label>
                {{ form.image5 }}
            </div>
            <div class="mb-3">
                <label for="id_image6" class="form-label">Image 6</label>
                {{ form.image6 }}
            </div>
            <div class="mb-3">
                <label for="id_image7" class="form-label">Image 7</label>
                {{ form.image7 }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

templates/product/Create Views/success.html
<!-- success.html -->
{% extends 'base/base.html' %}

{% block title %}Success{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2>Success</h2>
        <p>Your form has been submitted successfully!</p>
        <a href="{% url 'creation_dashboard_view' %}" class="btn btn-primary">Back to Dashboard</a>
    </div>
    
{% endblock %}